config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events, except: [:index] do
      resources :comments, only: [:create, :destroy]
  end
  post 'events/add_guest'
  post 'events/remove_guest'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:index, :show] do
      resources :friend_requests, only: [:index, :create, :update]
      resources :friends, only: [:index, :destroy]
  end
  get 'users/:id/createdevents', to: 'users#created_events', as: 'created_events'
  
   # API
   namespace :api, path: "",
                   constraints: { subdomain: "api" },
                   defaults: {format: :json} do
     namespace :v1 do
       resources :events
     end
   end

 end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  
  def index
    @friends = current_user.friends
  end

  def destroy
    @user = User.find(params[:user_id])
    @friend = User.find(params[:id])
    @user.friendships.find_by(friend_id: @friend.id).destroy
    flash[:success] = "Unfriended #{@friend.username}"
    redirect_to @friend
  end
  

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_friends.html.erb
<div class="friends-profile-container ">
  <h4><%= pluralize(@friends.count, 'friend') %></h4>
  <% @friends[0..8].each do |friendship| %>
    <%= link_to (friendship.friend) do %>
      <%= image_tag(friendship.friend.picture, class: 'friends-profile-pic') %>
    <% end %>
  <% end %>
  <%= link_to "See all", user_friends_path(@user.id), class: 'friends-link' %> 
</div>

app/views/friends/_unfriend.html.erb
<%= form_for [current_user, @user], url: user_friend_path(current_user), method: :delete do |f| %>
    <%= f.submit 'Unfriend', class: 'btn btn-primary form-control' %>
<% end %>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/index.html.erb
<h1>Friends#index</h1>
<p>Find me in app/views/friends/index.html.erb</p>