config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events, except: [:index] do
      resources :comments, only: [:create, :destroy]
  end
  post 'events/add_guest'
  post 'events/remove_guest'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:index, :show] do
      resources :friend_requests, only: [:index, :create, :update]
      resources :friends, only: [:index, :destroy]
  end
  get 'users/:id/createdevents', to: 'users#created_events', as: 'created_events'
  
   # API
   namespace :api, path: "",
                   constraints: { subdomain: "api" },
                   defaults: {format: :json} do
     namespace :v1 do
       resources :events
     end
   end

 end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :host, class_name: "User"
  has_and_belongs_to_many :guests, class_name: "User"
  has_many :comments
  
  
  default_scope { order(created_at: :desc) }

  mount_uploader :picture, PictureUploader

  validates :title, presence: true, length: {minimum: 3, maximum: 150}
  validates :body, presence:true ,length: { minimum: 25, maximum: 2500}
  validates :location, presence:true, length:{ minimum: 3 , maximum: 100}
  validates :date, presence:true

  def add_guest(user)
    self.guests << user
  end

  def remove_guest(user)
    self.guests.delete(user)
  end
end

app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < ApplicationController

  def index
     @events = Event.all
     render :json => @events


  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :logged_in_user, only: [:show, :new, :create, :edit, :destroy]

  def index
    @events = Event.paginate(page: params[:page], per_page: 12)
  end

  def show
    @event = Event.find(params[:id])
    @event_guests = @event.guests
    @comments = @event.comments
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosted_events.build(event_params)
    if @event.save
      flash[:success] = "#{@event.title} created"
      redirect_to @event
    else
      render 'new'
    end

  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "#{@event.title} updated"
      redirect_to @event
    else
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    flash[:success] = "#{@event.title} was successfully destroyed"
    @event.destroy
    redirect_to root_path
  end

  def add_guest
    @event = Event.find(params[:add][:event_id])
    @guest = User.find(params[:add][:guest_id])
    if !@event.guests.exists?(@guest.id)
      @event.add_guest(@guest)
      respond_to do |format|
          format.html do
            flash.now[:success] = "You joined #{@event.title}"
            redirect_to @event
          end
          format.js { flash.now[:success] = "You joined #{@event.title}" } 
      end
    else
      flash[:warning] = "You have already joined the event!"
      redirect_to @event
    end
  end

  def remove_guest
    @event = Event.find(params[:add][:event_id])
    @guest = User.find(params[:add][:guest_id])
    if @event.guests.exists?(@guest.id)
      @event.remove_guest(@guest)
      respond_to do |format|
          format.html do
            flash.now[:success] = "You left #{@event.title}"
            redirect_to @event
          end
          format.js { flash.now[:success] = "You left #{@event.title}" } 
      end
    else
      flash[:warning] = "Guest wasn't found."
      redirect_to @event
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :body, :location, :date, :guest_id, :picture)
  end

  def logged_in_user
    if !user_signed_in?
      flash[:warning] = "You must be logged in to create an event."
      redirect_to new_user_session_path
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
  require "html_truncator"
  
  def resume(content)
    HTML_Truncator.truncate(content, 20)
  end

end

app/views/events/_event_form.html.erb
<%= form_for(@event) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %><br />

  <%= f.label :body %>
  <%= f.trix_editor :body, class: "form-control"  %><br />

  <%= f.label :date %>
  <%= f.date_select :date, class:"form-control" %><br /><br />

  <%= f.label :location %>
  <%= f.text_field :location, class:"form-control" %><br /><br />

  <%= f.file_field :picture, class: "form-control" %><br />

  <%= f.submit yield(:button_text), class: "form-control btn btn-success" %>

<% end %>

app/views/events/_events_joined.html.erb
<h2>Events Joined</h2>
<% @events_joined.each do |event| %>
<div class="event col-md-12" style="height: 274px;">
  <div class="row title-bar">
    <div class="col-xs-10">
      <h4><%= event.title %></h4>
    </div>
    <div class="col-xs-2">
      <h4><%= link_to "Show", event_path(event.id) %></h4>
    </div>
  </div>
  <div class="row content">
    <% if event.picture? %>
      <div class="event-image col-xs-4">
        <%= image_tag event.picture.url %>
      </div>
      <div class="body col-xs-6 col-xs-offset-1">
        <p><%= resume(event.body).html_safe %></p>
      </div>
    <% else %>
      <div class="body col-xs-12">
        <p><%= resume(event.body).html_safe %></p>
      </div>
    <% end %>
    </div>
    <div class="row details">
      <div class="col-xs-12">
        <h4>
          <%= event.date.to_s.split(" ")[0].split("-").reverse.join("/") %>
          @ <%= event.location %>
        </h4>
      </div>
    </div>
  </div>
<% end %>

<%= will_paginate @events_joined %>

app/views/events/_join_leave.html.erb
<% if @event.guests.exists?(current_user.id) %>

    <h2> Leave </h2>
    <%= form_for(:add, url: events_remove_guest_path, remote: true)  do |f| %>
    
      <%= f.hidden_field :guest_id, value: current_user.id %>
      <%= f.hidden_field :event_id, value: @event.id %>
    
      <%= f.submit "Leave", class: "form-control btn btn-success" %>
    
    <% end %>
<% else %>
    <h2> Join </h2>
    <%= form_for(:add, url: events_add_guest_path, remote: true)  do |f| %>
    
      <%= f.hidden_field :guest_id, value: current_user.id %>
      <%= f.hidden_field :event_id, value: @event.id %>
    
      <%= f.submit "Join", class: "form-control btn btn-success" %>
    
    <% end %>
<% end %>

app/views/events/add_guest.js.erb
$("#join-leave").html('<%= escape_javascript(render 'events/join_leave') %>');
$("#flash").html('<%= escape_javascript(render 'layouts/flash') %>');
$("#guests").html('<%= @event.guests.map { |guest| guest.username }.join(", ") %>');

app/views/events/edit.html.erb
<% provide(:title, "Update #{@event.title}") %>
<% provide(:button_text, "Update") %>

<h1> Update <%= @event.title %></h1><br />

<%= render 'events/event_form.html.erb' %>

app/views/events/index.html.erb
<% provide(:title, "Home") %>
<h1>EventManager</h1>

<% @events.each_with_index do |event, index| %>
  <div class="event col-md-3 col-md-offset-1" style="height: 274px;">
    <div class="row title-bar">
      <div class="col-md-12">
        <h3>
          <%= event.title %>
          <%= link_to "Show", event_path(event.id) %>
        </h3>
      </div>
    </div>
    <div class="row content">
      <% if event.picture? %>
        <div class="event-image col-xs-4 col-md-6">
          <%= image_tag event.picture.url %>
        </div>
        <div class="body col-xs-6 col-md-6">
          <p><%= resume(event.body).html_safe %></p>
        </div>
      <% else %>
        <div class="body col-xs-12">
          <p><%= resume(event.body).html_safe %></p>
        </div>
      <% end %>
      </div>

      <div class="row details">
        <div class="col-md-6">
          <h4>
            <%= event.date.to_s.split(" ")[0].split("-").reverse.join("/") %>
            @ <%= event.location %>
          </h4>
        </div>

      </div>
    </div>
<% end %>

<%= will_paginate @events %>

app/views/events/new.html.erb
<% provide(:title, "Create an Event") %>
<%= provide(:button_text, "Create") %>

<h1> Create an Event </h1><br />

<%= render 'events/event_form' %>

app/views/events/remove_guest.js.erb
$("#join-leave").html('<%= escape_javascript(render 'events/join_leave') %>');
$("#flash").html('<%= escape_javascript(render 'layouts/flash') %>');
$("#guests").html('<%= @event.guests.map { |guest| guest.username }.join(", ") %>');

app/views/events/show.html.erb
<% provide(:title, "#{@event.title}") %>


<!-- Event -->
<div class="event container col-md-9">
  <div class="row title-bar">
    <div class="col-md-12">
      <h2><%= @event.title %>
        <%= link_to "Delete", event_path(@event.id), method: :delete,
                                                    data: { confirm: "Are you sure?" },
                                                    class: "pull-right" %>
        <%= link_to "Edit", edit_event_path(@event.id), class: "pull-right" %>
      </h2>
    </div>
  </div>
  <div class="row content">
    <% if @event.picture? %>
      <div class="event-image col-md-4">
        <%= image_tag @event.picture.url %>
      </div>
    <% end %>
    <div class="body col-md-8">
      <p><%= @event.body.html_safe %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h4 class="pull-right">
        <%= @event.date.to_s.split(" ")[0].split("-").reverse.join("/") %> || @
        <%= @event.location %>
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h2> Guests </h2>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <p id ="guests">
          <%= @event_guests.map { |guest| guest.username }.join(", ") %>
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Leave/Join button -->
<div id="join-leave" class="event container col-md-2 col-md-offset-1">
  <%= render 'events/join_leave' %>
</div>

<!-- Comments -->
<div class="event comments container col-md-12">
  <div class="row">
    <div class="col-md-12">
      <%= render "comments/comment_form" %>
    </div>
  </div>
  <div class="comments row">
    <div class="col-md-12">
      <h2 id="comment-count"><%= pluralize(@comments.count, "Comment") %></h2>
    </div>
    <div class="row">
      <div id="comments-body" class="col-md-8 col-md-offset-2">
        <%= render @event.comments %>
      </div>
    </div>
  </div>
  

</div>