config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events, except: [:index] do
      resources :comments, only: [:create, :destroy]
  end
  post 'events/add_guest'
  post 'events/remove_guest'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:index, :show] do
      resources :friend_requests, only: [:index, :create, :update]
      resources :friends, only: [:index, :destroy]
  end
  get 'users/:id/createdevents', to: 'users#created_events', as: 'created_events'
  
   # API
   namespace :api, path: "",
                   constraints: { subdomain: "api" },
                   defaults: {format: :json} do
     namespace :v1 do
       resources :events
     end
   end

 end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
  
   validates :user, presence: true
   validates :friend, presence: true, uniqueness: { scope: :user }
   validate  :not_self
   validate  :not_friends
   validate  :not_pending
  
  private
  
    def not_self
      errors.add(:friend, "can't be equal to user") if user == friend
    end
    
    def not_friends
      errors.add(:friend, 'is already added') if user.friends.include?(friend)
    end
    
    def not_pending
      errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
    end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
    
    before_action :set_friend_request, except: [:index, :create, :update]
    
    def index
        @incoming = FriendRequest.where(friend: current_user)
        @outgoing = current_user.friend_requests
    end
    
    def create
        @friend_request = current_user.friend_requests.build(friend_id: params[:user_id])
        if @friend_request.save
            flash[:success] = 'Friend request sent'
            redirect_to user_path(current_user.id)
        else
            flash[:danger] = "You can't sent a friend request to you'r self!"
            redirect_to user_path(current_user.id)
        end
    end
    
    def update
        @user = User.find(params[:user_id])
        @friend = User.find(params[:id])
        @friendship = @user.friendships.build(friend: @friend)
        if @friendship.save 
            @friend.friend_requests.find_by(friend: @user).destroy
            flash[:success] = "Added #{@friend.username} to friends."
            redirect_to user_path(current_user.id)
        else
            flash[:warning] = "brap"
        end
    end

end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_requests_sent_recieved.html.erb
 <p><%= link_to "#{ pluralize(@outgoing.count, 'friend request' ) } sent",
 user_friend_requests_path(current_user.id)  %></p>
 
 <p><%= link_to "#{ pluralize(@incoming.count, 'friend request') } received",
 user_friend_requests_path(current_user.id) %></p>

app/views/friend_requests/_send_request.html.erb
<%= form_for [@user, FriendRequest.new] do |f| %>
    <%= f.submit 'Add Friend', class: 'btn btn-primary form-control' %>
<% end %>

app/views/friend_requests/index.html.erb
<h1>Hello I'm the  INdex</h1>

<h3>Friend requests</h3>
<% @incoming.each do |request| %>
  <%= image_tag(request.user.picture) %>
  <%= request.user.username %>
  <%= link_to 'Add', user_friend_request_path(current_user.id, request.user.id), method: :put %>
<% end %>