config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events, except: [:index] do
      resources :comments, only: [:create, :destroy]
  end
  post 'events/add_guest'
  post 'events/remove_guest'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: [:index, :show] do
      resources :friend_requests, only: [:index, :create, :update]
      resources :friends, only: [:index, :destroy]
  end
  get 'users/:id/createdevents', to: 'users#created_events', as: 'created_events'
  
   # API
   namespace :api, path: "",
                   constraints: { subdomain: "api" },
                   defaults: {format: :json} do
     namespace :v1 do
       resources :events
     end
   end

 end

app/views/layouts/_flash.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% elsif alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% else %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/_sidebar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
        <ul class="nav sidebar-nav">
            <li class="sidebar-brand">
                <%= link_to "EventManager", root_path %>
            </li>
            <% if !user_signed_in? %>
              <li><%= link_to "Log in", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
            <% end %>
              <li><%= link_to "Events", root_path %></li>
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li class="dropdown-header"></li>
                  <li><%= link_to "Profile", user_path(current_user.id) %></li>
                  <li><%= link_to "Create an event", new_event_path %></li>
                  <li><%= link_to "See my created events.", created_events_path(current_user.id) %></li>
                </ul>
              </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% end %>
            <li>
                <a href="#">Contact</a>
            </li>
            <li>
                <a href="#">About</a>
            </li>
        </ul>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | EventManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bungee|Roboto" rel="stylesheet">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="wrapper">
        <div class="overlay"></div>

          <%= render 'layouts/sidebar' %>

          <div id="page-content-wrapper">
              <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                  <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
          <span class="hamb-bottom"></span>
              </button>
              <div class="container">
                  <div id="flash" class="row">
                    <%= render 'layouts/flash' %>
                  </div>

                        <%= yield %>
              
          </div>
          <!-- /#page-content-wrapper -->

      </div>

  </body>
</html>